### ISSUE TITLE
Customizing Connections

### ISSUE THREAD

**Issue by SergioBenitez** [bikeshedder/deadpool#108]
For some databases, certain configuration parameters must be set per-connection. The canonical example is SQLite with its `PRAGMA`-based configuration. With respect to `deadpool`, the ideal place to do this would be immediately before/after a connection is made to be placed in the pool. As far as I can tell, `deadpool` provides no such hook to accomplish this, short of writing a custom `Manager`. Is that correct?

For reference, the analog in `r2d2` is [`connection_customizer`](https://docs.rs/r2d2/0.8.9/r2d2/struct.Builder.html#method.connection_customizer).

**Comment by bikeshedder** [comment]
So far I've been trying to put as much configuration logic into the `Manager` implementations as possible.

I just wonder if that customizer needs to be `sync` or `async`... or maybe both? :thinking: 

What is the typical use case for such customizer? Does it issue DB queries or just change some options in the driver which are always non-blocking operations?

I am currently thinking of creating something like that:

```rust
/// An object modifier is called for every new connection that is
/// created by the manager.
pub enum ObjectCustomizer<T, W=T> {
    /// Use this variant if the function you are passing is know
    /// to never block. The function will be run as is for every
    /// new connection.
    NonBlocking(fn(obj: T) -> W),
    /// Use this variant if the given code is known to block.
    /// The function is wrapped inside [Runtime::spawn_blocking]
    /// making sure that it runs on a separate thread and doesn't
    /// block the async runtime.
    Sync(fn(obj: T) -> W),
    /// Use this variant if the given code is using async-await.
    Async(fn(obj: T) -> Pin<Box<dyn Future<Output=W> + 'static + Send>>),
}
```

I've been thinking about this for a bit now and quite like the idea of creating wrappers for the Manager instead of adding a new feature to the `Pool` implementation. e.g.

```rust
struct ManagerWrapper<T, W> {
    manager: Box<dyn Manager<T>>,
    customizer: ObjectCustomizer<T, W>,
}
```

Implementing a wrapping manager is no fun and way too many lines for a simple connection modification so I think it should be possible to use it like that:

```rust
let customizer = ObjectCustomizer::NonBlocking(|c| { c.set_some_parameter(); c });
let manager = Manager::new(...);
let wrapped_manager = customizer.wrap(manager);
let pool = Pool::new(wrapped_manager, 16);
...
```

What do you think of this approach?

**Comment by bikeshedder** [comment]
@SergioBenitez What do you think of #109?

**Comment by SergioBenitez** [comment]
@bikeshedder That approach feels simultaneously more complicated and less performant than I would hope. You've touched on the performance side on the PR. In terms of reducing complexity, what I would hope for is effectively a method/field on `Pool` or `Manager` that allows me to pass a callback which is then called every-time a connection is added to the pool.

From a usability/understandability standpoint, I would advocate for the change to `Pool`, perhaps via a change to `PoolConfig` or simply by adding another constructor to `Pool`. Internally, you'd store an `Option<Box<Fn(C) -> BoxFuture<Result<...>>>` (a boxed `async` fn from a connection type `C`). The cost is ~zero if it's not used (besides a check to see if customization is needed), and there's a single one-time `Box` cost if it _is_ used. This also results in zero overhead for implementations of `Manager` while being fully generic.

**Comment by bikeshedder** [comment]
I initially created that wrapper for the manager because I thought it could alleviate the need for the wrapper type of the pool. I like the wrapper approach a lot - mainly due to my recent usage of `warp` which pushes this idea to 11 - but for the sake of simplicity I'm opting for a configuration option rather than a wrapper for the manager.

@SergioBenitez I'm adding a `PoolBuilder` to the code. I never really liked that `runtime` is part of the config which doesn't make any sense to set from a config file. Now that there is a second configuration option that should not really be part of the config it's about time to add that.

I'm going to tackle #107 at the same time.

**Comment by bikeshedder** [comment]
Blocked by #110
