### ISSUE TITLE
Async Safety in `deadpool-diesel`

### ISSUE THREAD

**Issue by SergioBenitez** [bikeshedder/deadpool#112]
As far as I can tell, the `deadpool-diesel` crate does nothing to ensure that blocking database I/O executed by Diesel is executed in a non-blocking fashion, i.e, in a separate worker thread:

https://github.com/bikeshedder/deadpool/blob/2c7a0b7aee915e775f8d751e0a73ec884bae6f71/diesel/src/connection.rs#L59-L61

What am I missing?

**Comment by bikeshedder** [comment]
> What am I missing?

Nothing. I felt like doing `spawn_blocking` should be done by the user. But you're right, that this is error prone and in `deadpool-sqlite` I added an `interact` method for the exact same reason.

I guess it would be best to generalize the code for sync DB connections and reuse it for diesel as well. :thinking:

**Comment by SergioBenitez** [comment]
> I guess it would be best to generalize the code for sync DB connections and reuse it for diesel as well. thinking

I think doing this in/with `deadpool` is a bit misguided. Instead, in my opinion, if you want to enable `async` access to `synchronous` drivers, I would suggest wrapping `r2d2` in the same way that `rocket_sync_db_pools` does. Effectively every synchronous database driver already has an implementation compatible with `r2d2`, so you'd be rewriting (and maintaining) a bunch of code that already exists for no gain. If you instead create an `async` wrapper for `r2d2` that works for _every_ `r2d2`-compatible driver, you immediately provide `async` access to sync drivers for the entire ecosystem.

I'd be happy to assist with making the `rocket_sync_db_pools` non-specific to Rocket.

**Comment by bikeshedder** [comment]
I haven't thought about that. That does indeed sound awesome.

The manager of `deadpool` works slightly different from the `r2d2` one, but the differences should be easy to adapt.

---

I just finished reworking the `deadpool-diesel` code and using the `SyncWrapper` the implementation turned out to be tiny. Even the connection wrapper that implements `diesel::Connection` is no longer needed as the callback provides access to the unwrapped database connection object.

tbh. I'm not a big fan of the ergonomics of that `interact`/`run` interface. Error propagation is kinda ugly and it's easy to mess some types up and get compiler errors which are extremely confusing.

I've seen some code using `block_in_place` to work around such ergonomic issue. It's clever but dangerous at the same time as it creates the illusion that it's fine to call blocking sync code from async code without any worries.

**Comment by SergioBenitez** [comment]
> tbh. I'm not a big fan of the ergonomics of that `interact`/`run` interface. Error propagation is kinda ugly and it's easy to mess some types up and get compiler errors which are extremely confusing.

Absolutely. It's terrible.

> I've seen some code using `block_in_place` to work around such ergonomic issue. It's clever but dangerous at the same time as it creates the illusion that it's fine to call blocking sync code from async code without any worries.

Indeed. `async` is already difficult as it is, and `block_in_place` can be very surprising if the user doesn't understand the semantics, not to mention that it doesn't work at all if the runtime isn't multi-threaded. That being said, I can imagine having both a `run` and a `run_in_place` method, where you give the user the option. I'll explore implementing this in Rocket.

**Comment by bikeshedder** [comment]
I just created a new tracking issue for the `deadpool-r2d2` implementation: #116

**Comment by bikeshedder** [comment]
I'm closing this as the next release of `deadpool-diesel` will be based on `SyncWrapper` which enforces the use of the `interact` method just like the `deadpool-sqlite` crate.
