### ISSUE TITLE
Support for connection validation

### ISSUE THREAD

**Issue by trungda** [bikeshedder/deadpool#121]
Do we plan to have support for something similar to `keepaliveTime` in HikariCP? This is to periodically validate the connections in the pool. The connections might no longer be valid if the db backend is restarted.

**Comment by bikeshedder** [comment]
Most users don't need a active connection checking in the pool. They are cycled in a FIFO way in order to make sure everything is kept as "fresh" as possible.

Though there are two scenarios that I can think of where active connection refreshing can make a difference:

1. A service that has very little load (just a few requests per hour) which is still required to answer extremely fast. Thus all connections in the pool need to be in working condition and reconnecting hurts.
2. A service that handles less parallel requests than the available DB connections in the pool. In this case a small optimization would be to recycle the connections ahead of time and keep them available.

When writing deadpool I found that I want the guarantee of a "working" connection to be given as late as possible. I'd rather not hand out a connection that was checked 10s ago and considered to be in working condition which is dead by now. That's why I decided against implementing a clever background worker that removes dead connections, recycles connections ahead of time, etc.

In the end it resulted in a much simpler code base. Hence the name `deadpool` which I consider to be `dead simple` implementation wise.

---

That being said I've been thinking of adding some plugin/introspection API to `deadpool` so it's possible to add 3rd party code to work with the internal state of the pool. The actual objects live in a `std::sync::Mutex<VecDeque<_>>`. It's slightly dangerous to work with that directly as locking it without decrementing the semaphore first can lock up your executor.

A way to enable a 3rd party code to remove dead connections ahead of time could be a `get_pooled` method that returns all objects currently waiting in the pool. So for very simple health check that runs every minute you could write code like that:

```rust
const GC_TIMEOUT: usize = 60_000;
use tokio::time::{sleep, Duration};

fn spawn_pool_gc(pool: Pool) {
    tokio::spawn(async move {
        sleep(Duration::from_millis(GC_TIMEOUT)).await;
        for obj in pool.get_pooled() {
            if !some_clever_alive_check(obj) {
                Object::take(obj);
            }
        }
    });
}
```

This is a rather pragmatic approach and doesn't do any `ahead of time` recycling, adaptive pool resizing, etc.

---

Btw. you just gave me the idea for #123 which might provide very useful in this case, too.

Given a `creation_timestamp` you could remove objects older than `<duration>` from the pool.

**Comment by trungda** [comment]
Thank you for the answer! Where do we define the `get_pooled` method?

**Comment by bikeshedder** [comment]
@trungda I just created PR #131 and realized that it might actually be the wrong solution for your problem. I'm not going to merge this as it's probalby going to cause more ham then good in the long run. (See my comment in the PR for more details)

---

Now coming back to your original problem. You just want to throw away connections that are too old, right? Maybe #123 and a `PostRecycle` hook would actually be a better solution to your usecase:

Once it is merged you can write a hook like that:

```rust
struct MaxAge(Duration);
#[async_trait]
impl PostRecycle<T> for MaxAge {
    async fn post_recycle(&self, obj: &mut T, stats: &Statistics) -> Result<(), HookError<()>> {
        if (Instant::now().duration_since(stats.created) > self.0) {
            Ok(())
        } else {
            Err(HookError::Message("Max age reached".into()))
        }
    }
}
```

And then use it like that:

```rust
let pool = Pool::<T>::builder(manager)
    .post_recycle(MaxAge(Duration::from_seconds(60))
    .build()
    .unwrap();
```

The only difference here is that expired connections are still part of the pool until they are accessed the first time.

---

So there are actually two different problems:
1. Not reusing objects older than a given `max age` - this can be solved via #125 and #123
2. Removing objects from the pool older than `max age` - while #131 could be used for this I feel like locking the entire pool during clean up would be a way cleaner design.

What are your thoughts on that?

**Comment by trungda** [comment]
Sorry for the late response! Thanks a lot for your effort. I think ultimately, we need to remove old connections from the pool. Otherwise, we will have to at least access that connection in order for it to expire. This would impact latency of the framework.

**Comment by bikeshedder** [comment]
fyi. since the release of `deadpool 0.9` two weeks ago you can add a `pre_recycle` hook that throws away old connections. You can use the metrics of the object to know how many times it was recycled and when it was created. Since deadpool doesn't perform any ahead-of-time creation of objects there is little to be gained by the actual introspection feature. I'm going to close this issue in favor of #167 which describes a strategy for "ahead of time" object creation/recycling.
