### ISSUE TITLE
deadpool_diesel `interact` has fixed (wrong?) error type

### ISSUE THREAD

**Issue by kaj** [bikeshedder/deadpool#158]
The `interact` method on a `deadpool_diesel` connection seems to require that the result of the interaction is a `Result<T, deadpool_diesel::Error>`.  Since that error type can hold either a "conection failed" or a "failed to ping the database", I don't think that is intended?  I would like to use my own error type for the interaction.

```rust
    let db = pool.get().await?;
    let (title, _posted_at, _updated_at, content) = db
        .interact(move |db| Ok::<_, ViewError>({
            let arg = my_fuction(param)?;  // <--- (1)
            table.select((column1, column2))
                .filter(column.eq(arg))
                .first::<MyObj>(db)? // <-- (2)
        }))
        .await?; // <-- (3)
```
1. `my_function` returns a `Result<T, MyError>`,  so this is currently a compile error.  On an error here, I would like to get  an unmodified `MyError` returned at (3).
2. On an error here, interact claims that the connection manager failed to ping the database, with the actual database error as details.  I have a `impl From<diesel::Error> for MyError`, so I would like to get a `MyError` at (3).

I'm using deadpool-diesel version = "0.2.0", which adds deadpool version = "0.9.0" as a dependency.  I'm not sure if this is related to (or even a duplicate of) #133 .

(As an aside, the "async pool for sync connection" of deadpool_diesel 0.1 was absolutley marvelous.  With a postgres database on localhost and a multithreaded tokio runtime the theoretical problem of "blocking the executor" was fully solved in practice by having a larger number of executor threads than connections in the pool, so I'm not convinced (yet) that forcing the use of separate `interaction` is a good idea at all.)

**Comment by bikeshedder** [comment]
> but is there really a reason to have the Backend kind there at all?

Convenience. In my own tests I found it quite nice that I could write `conn.execute(...)?` without having to define my own error type that implements `From<diesel::result::Error>`. Since `InteractError` already needs two variants `Panic` and `Aborted` (the latter is currently not implemented) I found it natural to add the generic database error here too.

Maybe I should change the method signature like `tokio::spawn_blocking`. Returning a `Result<T, InteractError>` instead and if you return a `Result` from the closure the interact method just returns `Result<Result<_, _>, InteractError>`. That way you would be flexible to change the error type however you like and it doesn't need any DB or user specific variants in the `InteractError`.

**Comment by kaj** [comment]
> Convenience. In my own tests I found it quite nice that I could write `conn.execute(...)?` without having to define my own error type that implements `From<diesel::result::Error>`.

In cases where only a diesel Error is needed you wouldn't need to have an own error type, but you probably would need to specify the error type.  Unless the interaction function ends with the thing returning a diesel result, then you could just return that without a question mark and let it define the type of the interaction.

> Maybe I should change the method signature like `tokio::spawn_blocking`. Returning a `Result<T, InteractError>` instead and if you return a `Result` from the closure the interact method just returns `Result<Result<_, _>, InteractError>`.

Yes, that might be the best.  Given proper `From` implementations I think that would just require double question marks at (3) in my example.
