### ISSUE TITLE
CreatePoolError enum has unreachable Build variant

### ISSUE THREAD

**Issue by allan2** [bikeshedder/deadpool#164]
Pool creation always succeeds except for when there is a problem with the configuration.

The return type of `create_pool` is
```
pub enum CreatePoolError<C, B> {
    Config(C),
    Build(BuildError<B>),
}
```

Could we get rid of the `Build` case? Or go straight to the config error.
It would make it more clear that Deadpool doesn't check for errors on pool creation.

There is already a note in the README explaining that `pool.get().await.expect("DB connection failed")` can be used to catch build errors on startup.

**Comment by bikeshedder** [comment]
`CreatePoolError::Build` is used for one thing right now. When you specify timeouts and don't specify a `Runtime` the building fails with `CreatePoolError::Build(BuildError::NoRuntimeSpecified)`. I could get rid of that but every call to `Poll::get` would then return an error immediately because of the missing runtime.

The other variant `BuildError::Backend` was used to return errors from the `create_pool` method when `CreatePoolError` didn't exist, yet. It is indeed an oversight and should probably be removed. Even if it makes sense to have this it should still be changed so it uses its own generic type and doesn't reuse `Manager::Error` which is almost guaranteed to be wrong.

This is something that needs to be sorted out before 1.0. With #166 this code needs to be touched anyways. I don't think `PoolBuilder` is actually the right pattern. I've written down my ideas in #166.

For the time being it probably makes sense to mark `BuildError::Backend` as deprecated and remove it in the next breaking release of deadpool. I plan to release `1.0` by the end of this year, but there is no defacto deadline for that. Just myself wishing for a very stable 1.0 release. :grinning:
