### ISSUE TITLE
A Pool of Pools

### ISSUE THREAD

**Issue by elpiel** [bikeshedder/deadpool#165]
Hey,
I'm working on a testing setup that creates a Pool for a concrete database (postgres) for each test.
This way I can comfortably work with Pool in my query functions while ensuring separation of the test cases.

I'm facing a problem though and I can't figure out a good way to tackle it.
Every now and then the tokio_postgres::Client gets closed (https://docs.rs/tokio-postgres/0.7.5/tokio_postgres/struct.Client.html#method.is_closed) and my tests are failing.

Is there something I am missing on how deadpool & deadpool_postgres work that's causing the connection to get closed?

https://github.com/AmbireTech/adex-validator-stack-rust/blob/ec0d6a5694952369e094111de3cc65103efa2529/sentry/src/db.rs#L262-L354

**Comment by bikeshedder** [comment]
`deadpool` checks the connection right before returning it. The default recycling method of `deadpool_postgres` is `RecyclingMethod::Fast` which just performs a `Client::is_closed` check. I've heard reports where `Client::is_closed` returns `false` but the next query fails nonetheless.

Since you already use `RecyclingMethod::Verified` that can't be the issue though. `deadpool_postgres` essentially guarantees that every objects returned by it is in useable condition when using `RecyclingMethod::Verified` as it performs an actual query right before returning the connection.

Does maybe the PostgreSQL log tell you why the connection was closed?

**Comment by bikeshedder** [comment]
btw. you should be able to upgrade `deadpool-postgres` to version `0.10` and remove the `deadpool` dependency. The newest `deadpool-*` crates are built so that you don't need to use the `deadpool` crate at all. Everything you need should be reexported by the `deadpool-*` crate already.

With the latest deadpool version there are three hooks that you can use to add some custom validation logic: `post_create`, `pre_recycle` and `post_recycle`. You can also check the newly added `Object::metrics` to see how many times a closed connection was recycled.

**Comment by elpiel** [comment]
I still haven't found time to fix this, but many many thanks for the guides.

Also, I see that it's still required to have `tokio_postgres` as a dependency (when enabling features) even though it's re-exported in `deadpool-postgres`. Maybe instead of adding `tokio_postges`, the same features could be added to `deadpool-postgres` which will enable `tokio_postgres` features?
This could be particularly useful when you don't need to deal with `tokio_postgres` directly.

> Does maybe the PostgreSQL log tell you why the connection was closed?

I, honestly, haven't checked Postgres at all :sweat_smile: and this is a good starting point!

**Comment by bikeshedder** [comment]
> Also, I see that it's still required to have tokio_postgres as a dependency (when enabling features) even though it's re-exported in deadpool-postgres. Maybe instead of adding tokio_postges, the same features could be added to deadpool-postgres which will enable tokio_postgres features?

This is something that has been raised before. I created a new tracking issue for that:

- #169

**Comment by bikeshedder** [comment]
@elpiel Did you find the cause of the problem? Is it a deadpool issue or can this be closed?

**Comment by elpiel** [comment]
> @elpiel Did you find the cause of the problem? Is it a deadpool issue or can this be closed?

I'm working on different tasks at the moment and I haven't taken any actions to fix the issue yet.

**Comment by bikeshedder** [comment]
I haven't heard back from you for quite some time now.

Feel free to re-open this if you're able to reproduce this. A test showing the broken behavior would be highly appreciated. Feel free to create a PR for that. :+1:

**Comment by elpiel** [comment]
@bikeshedder will do that once I'm finished with my urgent tasks.

**Comment by acim** [comment]
I have similar problem although I am not sure if it is the same one. I don't get client disconnection that often, like described in this issue, but it happens sometimes. After 24 hours of running some data ingress there are better chances for this. Once I got the whole pool disconnected.

` 
{"level":"INFO","ts":"2022-04-12T17:09:50.347Z","msg":"Connection could not be recycled: Connection closed"}
{"level":"WARN","ts":"2022-04-12T17:09:50.367Z","msg":"Connection error: connection closed"}
`

What's the purpose of [this recycle method](https://github.com/bikeshedder/deadpool/blob/0835f03886e0021e0d8ceeac8f87ec7753832e44/postgres/src/lib.rs#L123)? Shouldn't it create new tokio_postgres client when one is closed? If not, how to handle such situations?

**Comment by bikeshedder** [comment]
The purpose of the `recycle` method is to recycle connections **at retrieval time**. Since deadpool doesn't have any background worker it can't do any ahead-of-time recycling. Dead connection are left in the pool until they are retrieved the next time. If you have a pool that's left unused for a few hours chances are that all connections are dead and the recycle method will be called for every single connection in the pool prior to creating new connections.

This is clearly optimized for high contested pools where objects rarely stay longer than a few milliseconds in the pool.

In the current `main` branch I added a new `retain` method which allows removal of old connections so you can implement ahead-of-time recycling yourself:

```rust
tokio::spawn(async move {
    loop {
        tokio::time::sleep(interval).await;
        pool.retain(|_, metrics| metrics.last_used() < max_age);
    }
});
```

See: https://github.com/bikeshedder/deadpool/blob/0835f03886e0021e0d8ceeac8f87ec7753832e44/src/managed/mod.rs#L525

The first argument to the closure is the actual object. In the case of `tokio-postgres` you could return`!obj.is_closed()` instead of relying on the metrics. `Client::is_closed` is a sync method and therefore usable with the `Pool::retain` method.

**Comment by elpiel** [comment]
I've recently made a new Pool for mongodb and experienced an issue with the connections again. The easy solution was to create a new connection on every recycling and override the current Pool object connection.

I have to figure out a way to reliably test this and see what's going wrong. Here it was even more bizarre because I was having an issue only on CI but not locally.
