### ISSUE TITLE
Redis Pool without configuration file

### ISSUE THREAD

**Issue by cuyler** [bikeshedder/deadpool#229]
Is there an example somewhere of creating a deadpool_redis pool manually (by hand) without using a configuration file-esque method?

Creating the structures by hand mostly works except for "connection" on deadpool_redis::Config. There also doesn't seem to be any example on how to use the builder without using it via a configuration into.

**Comment by cuyler** [comment]
Thanks @bikeshedder ! That would be helpful, I think. the scenario is to just manually make all of the attributes of the connection by hand, so a flattened struct would be dope.

**Comment by bikeshedder** [comment]
I just found the real cause of your troubles. I forgot to export the `ConnectionInfo` and `RedisConnectionInfo` from the crate root.

The structs are marked as public but the `config` module is not. Normally this should give a linter error due to an non-public type used in a public interface.

I'll take care of this and release a new `deadpool-redis` version asap.

**Comment by cuyler** [comment]
TYSM!
