### ISSUE TITLE
tokio-postgres exposing notice_callback

### ISSUE THREAD

**Issue by to266** [bikeshedder/deadpool#260]
Seems that the deadpool `Config` does not expose the [`notice_callback`](https://github.com/sfackler/rust-postgres/blob/790af54a0fdd5c487e77dc9a25d82921ee31ffe6/postgres/src/config.rs#L373) method, and thus it's not possible (or at least not immediately clear how) to receive the notices.

It's also worth considering if this should only be configured for a particular connection plucked from the pool, as passing the same handler to everything may not be the wanted behavior. In that case a bit of documentation explaining the situation might be beneficial for users.

**Comment by to266** [comment]
Actually my bad - the `notice_callback` is not exposed by `tokio-postgres` crate
https://github.com/sfackler/rust-postgres/issues/1045

**Comment by to266** [comment]
Just for completeness - as https://github.com/sfackler/rust-postgres/issues/1045 points out, in fact it is possible with `tokio-postgres` connections, but it's not exposed on the deadpool side.

IMO it makes sense both in terms of "keeping deadpool dead simple", as well as due to the shared nature of connections in the pool setting.

What _might_ be nice, is for a pool to provide a method to spawn `(client, connection)` pair as per the settings it already has, and then the user is very much aware that the two are __outside__ the pool context, but further customization (such as driving the connection differently and fetching the messages) is possible,

**Comment by bikeshedder** [comment]
Currently the connect function does perform a `connection.await` and which renders the connection object unusable otherwise.

The easiest way to implement this feature would be to call `poll_message` repeatedly and dispatch notifications via a [broadcast channel](https://docs.rs/tokio/latest/tokio/sync/broadcast/index.html).

The only "danger" here would be that users could keep a copy of the `Receiver` by accident and receive notifications from an already returned client. A way around that would be to not expose the receiver object directly but tie the lifetime to it to the `ClientWrapper`. That however could result in a rather bad DX.

I think a good compromise would be to place the `Sender` in an `Mutex` and replace it every time the object is returned to the pool. That way futures still reading from it would get a `RecvError::Closed` and could terminate properly. By using a `Mutex<Option<Sender>>` the underlying channel could even be created lazily.

A simple `std::sync::Mutex` should be fine, as it is not going to be heavily contested. If that does cause issues an `ArcSwap` could be used instead.

I quite like the idea of that feature.

There is just one small gotcha. Since there is no active recycling task the connection will keep listening to notifications until it is recycled as part of `Pool::get`. Now that I think about this it could be possible to issue queries to the connection even without calling `.await`. The link between `Connection` and `Client` is a channel and it should be possible to execute queries without having to wait for them.

**Comment by LukasKalbertodt** [comment]
> What _might_ be nice, is for a pool to provide a method to spawn `(client, connection)` pair as per the settings it already has, and then the user is very much aware that the two are **outside** the pool context, but further customization (such as driving the connection differently and fetching the messages) is possible,

I quite like that idea. I suppose the most common usage of async notifications is to invalidate caches. And in that scenario, only one connection to the DB needs to execute `LISTEN channel` and poll async notifications. The proposed API gives one full control over this. And it's actually quite similar to what I will have to do in absence of such an API: just use `tokio-postgres` to create a separate connection to the DB. That's just a bit more annoying as I have to create a second config struct value.

The approach by @bikeshedder would work too of course. One would only execute `LISTEN channel` on one connection, but (if I understand you correctly), deadpool will poll messages on all connections.

Anyway, I'm also interested in this feature.

**Comment by bikeshedder** [comment]
> (...) That's just a bit more annoying as I have to create a second config struct value.

You can call [Config::get_pg_config](https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.Config.html#method.get_pg_config) for that very use case.

> The approach by @bikeshedder would work too of course. One would only execute LISTEN channel on one connection, but (if I understand you correctly), deadpool will poll messages on all connections.

My idea was to create a layer on top of `LISTEN`/`NOTIFY` adding a `listen()` method to the `ClientWrapper`. Internally the `ClientWrapper` communicates with the underlying implementation via channels. When the `ClientWrapper` is dropped so are the listeners calling `UNLISTEN` automatically.

tbh. I still wonder why anyone would want to use a pool for a connection that is borrowed once and never returned. The entire reason for having a pool in the first place is kinda gone, isn't it?
