### ISSUE TITLE
Identifying connections in hooks

### ISSUE THREAD

**Issue by 50U10FCA7** [bikeshedder/deadpool#308]
In current hooks API there's no way to identify connection being created/recycled.

Connection identification is required for the following use cases:
- collecting metrics per connection;
- keeping some state of the connection.

Example (pseudo code):
```rust
type States = HashMap<ConnectionId, MyConnectionState>;

/// State of connection invalidating statements cache each 5 seconds.
struct MyConnectionState {
    last_cache_invalidation: Instant,
    connection_handle: Weak<StatementCache>, // Hold reference to detect connection being dropped.
}

impl MyConnectionState {
    fn post_create(conn: &mut ClientWrapper, m: &Metrics, states: States) -> HookResult<BackendError> {
        states.retain(|_, s| s.connection_handle.upgrade().is_some()); // Remove dropped connections.
        states.insert(m.connection_id, Self {
            last_cache_invalidation: Instant::now(),
            connection_handle: conn.statements_cache.downgrade(),
        });
    }

    fn post_recycle(conn: &mut ClientWrapper, m: &Metrics, states: States) -> HookResult<BackendError> {
        let now = Instant::now();
        if states.get(m.connection_id).last_cache_invalidation > now {
            return Ok(());
        }

        states.get_mut(m.connection_id).last_cache_invalidation = now + Duration::from_secs(5); // Update timeout.
        conn.statements_cache.clear(); // Clear cache.

        Ok(())
    }
}

// ..

let states = States::new();

let pool = pool_cfg.builder()
    .post_create(move |conn, m| MyConnectionState::post_create(conn, m, states.clone()))
    .post_recycle(move |conn, m| MyConnectionState::post_recycle(conn, m, states.clone()))
    // Maybe we should add a `pre_close` to avoid holding `Weak<StatementCache>`?
    .build();
```

**Comment by bikeshedder** [comment]
It looks like you're looking for a way to add additional data to objects? The easiest (and most performant) way is to create a wrapper struct and return that from the pool.

Some time ago I ran into the exact same problem with the `deadpool-postgres` crate where I needed to clear the statement cache for any connection currently managed by the pool:

- See: https://github.com/bikeshedder/deadpool/commit/117f965c14c8a2b28ed96a9702ccace124cc3371

Just create a wrapper object containing the actual connection and put all the other things you need in there:

https://github.com/bikeshedder/deadpool/blob/632044965bf7110b0f9ffb0be16bc431f6b4cd08/postgres/src/lib.rs#L380-L390

For convenience don't forget to implement `Deref` and `DerefMut`, too:

https://github.com/bikeshedder/deadpool/blob/632044965bf7110b0f9ffb0be16bc431f6b4cd08/postgres/src/lib.rs#L442-L454

Also make sure to implement the `Manager::detach()` method so you don't end up keeping references to objects that have been taken via `Object::take()`. See:

https://github.com/bikeshedder/deadpool/blob/632044965bf7110b0f9ffb0be16bc431f6b4cd08/postgres/src/lib.rs#L155-L157

----

I'm still thinking about a more straightforward way to provide access to objects already handed out. It would be nice if one could gain some kind of Handle to objects currently outside of the pool. That handle would than allow access to the `Metrics`, user specific data (such as caches) and provide a way to mark objects as `do_not_recycle` so that it doesn't even get returned to the pool when dropped.

**Comment by 50U10FCA7** [comment]
@bikeshedder Thanks for answering. Got your point.

Just wrap an existing `deadpool::Manager` changing the `Object` type it manages:

```rust

struct MyClient {
    pub inner: deadpool_postgres::ClientWrapper,
    pub my_unique_id: Uuid,
}

struct MyManager(deadpool_postgres::Manager);

impl deadpool::Manager for MyManager {
    type Type = MyClient;
    type Err = <deadpool_postgres::Manager as deadpool::Manager>::Err;

    async fn create(&self) -> Result<ClientWrapper, Error> {
        Ok(MyClient {
            id: Uuid::new_v4(),
            inner: self.0.create()?,
        })
    }

    // ...other methods
}
```

Looks a little cumbersome, but I think it's the best alternative to do this for now.

Closing this issue as resolved.

**Comment by bikeshedder** [comment]
If you're building your own statement cache it might actually make sense to fork the `deadpool_postgres` code and use `tokio_postgres` directly as it already got a statement cache built-in and you're paying the price of statement cache management code twice.

I'm curious. What makes your statement cache different from the one from `deadpool-postgres`? Are there features missing?

**Comment by bikeshedder** [comment]
btw. I'm in no way against adding a unique object identifier to the pooled objects. I'll definitely want to add this feature as it sounds useful. Could be useful for debugging, too. I just added a separate tracking issue for this feature:

- #310

**Comment by 50U10FCA7** [comment]
@bikeshedder

> I'm curious. What makes your statement cache different from the one from deadpool-postgres? Are there features missing?

I'm not trying to reimplementing statements caches or something. Just need to invalidate statements caches for connection each N minutes (for testing purposes). This requires to keep `time::Instant` of the last (or next) invalidation for each connection. Like in the header's example:

```rust
    fn post_recycle(conn: &mut ClientWrapper, m: &Metrics, states: States) -> HookResult<BackendError> {
        let now = Instant::now();
        if states.get(m.connection_id).last_cache_invalidation > now { // `last_cache_invalidation` must be per-connection variable.
            return Ok(());
        }

        states.get_mut(m.connection_id).last_cache_invalidation = now + Duration::from_secs(5);
        conn.statements_cache.clear();

        Ok(())
    }
```

Also, for tracking whole connection lifecycle with `tracing-rs` it needs to be identified somehow:

```rust
#[tracing::instrument(skip_all, fields(id = conn.some_unique_id))]
fn post_recycle(conn: &mut ClientWrapper, m: &Metrics, states: States) -> HookResult<BackendError> {
}
```
