### ISSUE TITLE
Changes to the declaration of Manager `fn create(&self)`

### ISSUE THREAD

**Issue by pangzhenzhou** [bikeshedder/deadpool#327]
I noticed that the Manager's create and recycle declarations have changed since version 0.11.0. Instead of using the more simple 

```async fn create(&self) -> Result<Self::Type, Self::Error>```

I want to ask:
1. what is the reason for doing this
2. clippy throws an error

Thanks !!

**Comment by bikeshedder** [comment]
The problem with using `async fn` is that it's not possible to add the `Send` maker trait to the returned Future.

Where does `clippy` throw an error? I just tried upgrading to Rust 1.78 with the latest clippy version and I don't get any clippy warnings for the entire workspace.

btw. any code implementing the `Manager` trait can use the `async fn` format:

https://github.com/bikeshedder/deadpool/blob/2a584a99fa6d80921f6428b7c5e7e6dc06b8e0a9/postgres/src/lib.rs#L149

It's really just the trait definition that uses `-> impl Future<...> + Send` so that the returned future is required to be `Send`.

**Comment by pangzhenzhou** [comment]
Got it. Thx
