### ISSUE TITLE
deadpool postgres: config type for `load_balance_hosts` is private

### ISSUE THREAD

**Issue by kamulos** [bikeshedder/deadpool#375]
I can't find a way to set the option `load_balance_hosts` when creating a deadpool postgres `Config` object. The type seems to be private. Did I overlook something?

**Comment by bikeshedder** [comment]
You can access this field like any other field in the `Config` struct:

https://github.com/bikeshedder/deadpool/blob/ac5d03dd295f99f1895d13ae798320dfa1d4667f/postgres/src/config.rs#L108-L109

Did you maybe end up with a [`tokio-postgres::Config`](https://docs.rs/tokio-postgres/latest/tokio_postgres/config/struct.Config.html) instead?

Unlike `tokio-postgres` which uses the builder pattern for the config I decided against it in `deadpool-postgres`. Using a plain struct makes integration with `serde` so much easier. I consider the builder pattern to be harmful for config structures and that's why I don't use it for any config structures in the `deadpool-*` crates.

**Comment by kamulos** [comment]
I meant how can I create an object to put into the `load_balance_hosts` member? I would need to create an `Option<deadpool_postgres::config::LoadBalanceHosts>`, but the `deadpool_postgres::config` is private. So the type is out of reach for me.

This is also visible in [the documentation](https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.Config.html#structfield.load_balance_hosts) where the `LoadBalanceHosts` type is not clickable.

**Comment by bikeshedder** [comment]
Oh my. You're right. :facepalm: 

Normally errors like that should be caught by [`exported_private_dependencies`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#exported-private-dependencies) but for some reason it doesn't seam to work for re-exports.

This check doesn't seem work if a type is `pub` but the module where it is contained in is private only to be re-exported by the parent module or crate root.

**Comment by bikeshedder** [comment]
I just published `deadpool-postres` version `0.14.1` which adds the missing re-export of [LoadBalanceHosts](https://docs.rs/deadpool-postgres/0.14.1/deadpool_postgres/enum.LoadBalanceHosts.html):

:package: https://crates.io/crates/deadpool-postgres/0.14.1

Thanks for reporting this! :thumbsup:
