### ISSUE TITLE
How to commit a transaction?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [bikeshedder/deadpool#5]
Transaction#commit moves the transaction, but an owned reference to the transaction doesn't seem to be available. Am I missing something, or are transactions unusable with this pool?

**Comment by bikeshedder** [comment]
I totally messed that up. `commit` and `rollback` were unreachable via `Deref<Transaction>` because they consume `self`. I added a consuming `commit` and `rollback` function to the `Transaction` wrapper and also improved the tests.

I just released version `0.2.3` which fixes this. The crate finally also has proper documentation on docs.rs. :tada:
