### ISSUE TITLE
postgres GenericClient or equivalent?

### ISSUE THREAD

**Issue by triptec** [bikeshedder/deadpool#56]
Hello!
I'm wondering if there's any possibility of having a function signature that could take either a ClientWrapper or Transation? From what I gather that's what the GenericClient trait (https://docs.rs/tokio-postgres/0.5.4/src/tokio_postgres/generic_client.rs.html#14-69) is created for?

My use-case is that in test's I'd like to pass a Transaction that I can rollback in the end. 
Thanks

**Comment by bikeshedder** [comment]
That trait was added quite recently. For some reason @sfackler decided to make that trait sealed so I can't implement it for the `ClientWrapper`. This shouldn't be a problem though because both `Client` (which is a type alias for `deadpool::Object<ClientWrapper, Error>` and `ClientWrapper` support dereferencing:

```
let generic_client: &tokio_postgres::GenericClient = &**client;
```

Actually this should do the trick as well:

```
let generic_client: &tokio_postgres::GenericClient = &client;
```

This **should** work, but right now it causes some issues. Probably because of how `async_trait` rewrites the traits:

```
error[E0038]: the trait `tokio_postgres::generic_client::GenericClient` cannot be made into an object
   --> postgres/tests/postgres.rs:152:12
    |
152 |     let _: &dyn tokio_postgres::GenericClient = &***client;
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio_postgres::generic_client::GenericClient` cannot be made into an object
    | 
   ::: /home/bikeshedder/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.2/src/generic_client.rs:16:14
    |
16  |     async fn execute<T>(&self, query: &T, params: &[&(dyn ToSql + Sync)]) -> Result<u64, Error>
    |              ------- the trait cannot be made into an object because method `execute` has generic type parameters
...
21  |     async fn execute_raw<'b, I, T>(&self, statement: &T, params: I) -> Result<u64, Error>
    |              ----------- the trait cannot be made into an object because method `execute_raw` has generic type parameters
...
28  |     async fn query<T>(&self, query: &T, params: &[&(dyn ToSql + Sync)]) -> Result<Vec<Row>, Error>
    |              ----- the trait cannot be made into an object because method `query` has generic type parameters
...
33  |     async fn query_one<T>(
    |              --------- the trait cannot be made into an object because method `query_one` has generic type parameters
...
42  |     async fn query_opt<T>(
    |              --------- the trait cannot be made into an object because method `query_opt` has generic type parameters
...
51  |     async fn query_raw<'b, T, I>(&self, statement: &T, params: I) -> Result<RowStream, Error>
    |              --------- the trait cannot be made into an object because method `query_raw` has generic type parameters
```

**Comment by bikeshedder** [comment]
I do consider this a bug though I feel like this is actually `tokio-postgres` problem. Right now I can't even declare a function which takes a `&dyn tokio_postgres::GenericClient` as argument because of this:

```
error[E0038]: the trait `tokio_postgres::generic_client::GenericClient` cannot be made into an object
   --> postgres/tests/postgres.rs:155:32
    |
155 | fn _use_generic_client(client: &dyn tokio_postgres:: GenericClient) {
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio_postgres::generic_client::GenericClient` cannot be made into an object
...
```

**Comment by sfackler** [comment]
The methods of the trait have type parameters, so it is not object safe. There's nothing special about async-trait going on. You can instead use an `impl GenericClient` rather than `dyn GenericClient`.

**Comment by bikeshedder** [comment]
@sfackler Thanks a lot. I really need to read once again about the differences of `impl` and `dyn`.

@triptec If you just replace `dyn` by `impl` it works as expected:

```rust
#[tokio::main]
#[test]
async fn test_generic_client() {
    let pool = create_pool();
    let client = pool.get().await.unwrap();                                                                                                                                                      
    _use_generic_client(&**client);
}
_use_generic_client(client: &impl tokio_postgres:: GenericClient) {
    // nop
}
```

I just added this to the tests to show its usage: https://github.com/bikeshedder/deadpool/commit/a6f89536673ffe70cd399a307d337d80b8505d4e

**Just one warning:** When using GenericClient the statement cache won't be used as you're now circumventing the ClientWrapper which does that for you.

**Comment by triptec** [comment]
@bikeshedder Yeah, I've understood as much. But is there anything in the way of having a deadpool_postgres::GenericClient trait that's implemented on clientwrapper and transaction?

**Comment by bikeshedder** [comment]
It is no problem to add this to `deadpool-postgres`.

If you need this very soon, feel free to create a PR for that. Otherwise I might find some time to add this over the weekend. No guarantees though.

I'm just adding an `enhancement` label for now.

**Comment by triptec** [comment]
I’m just started my vacation so I won’t be “needing” anything for 6 weeks and I’d like to give it a try if you don’t find it that you need it.

**Comment by bikeshedder** [comment]
I just released `deadpool-postgres 0.8.0` which includes a new way how the statement cache can be accessed.

`ClientWrapper.statement_cache` and `Transaction.statement_cache` are now an `Arc<StatementCache>` and since `tokio-postgres 0.7.1` you can call the `client` method which gives you the underlying `tokio_postgres::Client` for both `Client` and `Transaction` objects. Generic code that also needs access to the `StatementCache` can just accept the cache as a separate parameter.

I considered adding a `GenericClient` to `deadpool-postgres` as well, but feel like there is little to be gained by that now that the `StatementCache` is now wrapped in an `Arc`.

Please let me know what you think.

**Comment by bikeshedder** [comment]
I'm closing this as I currently see the need for a `GenericClient` trait.

Feel free to reopen this issue and/or create a PR for this if you need this feature.

**Comment by OskarPersson** [comment]
@bikeshedder How would you use this to create a Actix-web server with app data being either a pool or a transaction object?

For example, in production I want to create the server using a pool as shown in https://github.com/bikeshedder/deadpool/blob/master/examples/postgres-actix-web/src/main.rs

But in my tests I want to create the same server but with a transaction object instead that can be used with the same handlers. 

That way I can in each test

1. create a transaction
2. add some data
3. launch the server with the same transaction object
4. make a request to a handler and at the end of the test, rollback the transaction.

**Comment by bikeshedder** [comment]
`deadpool_postgres::ClientWrapper` implements `Deref` giving you access to the underlying `tokio_postgres::Client`.
`deadpool_postgres::Transaction` implements `Deref` giving you access to the underlying `tokio_postgres::Transaction`. You can either use `tokio_postgres::GenericClient` or if you don't need nested transactions you can call the `client()` method which doesn't need boxed futures.

The only caveat here is that you need to pass the `StatementCache` alongside of it. If you don't need/want the statement cache this is a non issue. Otherwise just use the `Client::statement_cache` and pass this as a second argument to your functions.

https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.StatementCache.html

A proper `deadpool_postgres::GenericClient` trait would provide a nicer API for sure.

Slightly off topic: I don't consider the split into two structures (`Client` and `Transaction`) a huge win. I've experimented changing the implementation of `transaction` to return a `Client` instead of a `Transaction`. There are a few methods in the `Transaction` struct that don't make sense for transactions. Those would need to return an error if there is no transaction in progress. Apart from that the API would look and behave basicly the same except there would be no longer a need for `GenericClient`.

If you're interested in a `GenericClient` trait feel free to open a PR. Personally I think the `transaction` method should just return another `ClientWrapper` hiding the almost neglectibe implementation differences between `Client` and `Transaction`.

I might be revisiting this in the very near future as I'm need that feature myself.

**Comment by bikeshedder** [comment]
Sorry. I missed one important bit in your initial question:
> (...) with **app data** being either a pool or a transaction object (...)

I don't see why you would ever want to write an actix-web handler that accepts either a connection or transaction as argument. That's a strange requirement to have. :thinking: 

This is more an actix question than it is a deadpool one. Feel free to open a new issue with a basic example to showcase what you're trying to do (it doesn't need to compile). Even if it's not related to deadpool I or some other user might still be able to help you with your problem.

**Comment by OskarPersson** [comment]
Well its not maybe specifically a actix question but it might be more of a general webserver question, regardless if its actix or something else.

I only want to do this for tests where I can force all of the sql interaction (both inside the tests and those executing in a handler on the server once requested from the test). Otherwise when running the application outside of tests I want to use the regular connection pool

**Comment by DmitryBochkarev** [comment]
Hi there!

For my little project, I've been introduced following trait, and we can use it for starting the implementation of GenericClient. If it can wait, I can create PR for that

```rust
use async_trait::async_trait;
use tokio_postgres::Error;

// https://docs.rs/tokio-postgres/0.7.0/src/tokio_postgres/generic_client.rs.html#14-71
#[async_trait]
pub trait PgClient {
    async fn prepare(&self, query: &str) -> Result<tokio_postgres::Statement, Error>;
    async fn execute<T>(
        &self,
        query: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<u64, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send;
    async fn query_one<T>(
        &self,
        statement: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<tokio_postgres::Row, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send;
    async fn query_opt<T>(
        &self,
        statement: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<Option<tokio_postgres::Row>, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send;
    async fn query<T>(
        &self,
        query: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<Vec<tokio_postgres::Row>, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send;
}

#[async_trait]
impl PgClient for deadpool_postgres::Transaction<'_> {
    async fn prepare(&self, query: &str) -> Result<tokio_postgres::Statement, Error> {
        let tx: &tokio_postgres::Transaction = &self;
        tx.prepare(query).await
    }

    async fn execute<T>(
        &self,
        query: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<u64, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let tx: &tokio_postgres::Transaction = &self;
        tx.execute(query, params).await
    }

    async fn query_one<T>(
        &self,
        statement: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<tokio_postgres::Row, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let tx: &tokio_postgres::Transaction = &self;
        tx.query_one(statement, params).await
    }

    async fn query_opt<T>(
        &self,
        statement: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<Option<tokio_postgres::Row>, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let tx: &tokio_postgres::Transaction = &self;
        tx.query_opt(statement, params).await
    }

    async fn query<T>(
        &self,
        query: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<Vec<tokio_postgres::Row>, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let tx: &tokio_postgres::Transaction = &self;
        tx.query(query, params).await
    }
}

#[async_trait]
impl PgClient for deadpool_postgres::Client {
    async fn prepare(&self, query: &str) -> Result<tokio_postgres::Statement, Error> {
        let client: &tokio_postgres::Client = &self;
        client.prepare(query).await
    }

    async fn execute<T>(
        &self,
        query: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<u64, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let client: &tokio_postgres::Client = &self;
        client.execute(query, params).await
    }

    async fn query_one<T>(
        &self,
        statement: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<tokio_postgres::Row, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let client: &tokio_postgres::Client = &self;
        client.query_one(statement, params).await
    }

    async fn query_opt<T>(
        &self,
        statement: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<Option<tokio_postgres::Row>, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let client: &tokio_postgres::Client = &self;
        client.query_opt(statement, params).await
    }

    async fn query<T>(
        &self,
        query: &T,
        params: &[&(dyn tokio_postgres::types::ToSql + Sync)],
    ) -> Result<Vec<tokio_postgres::Row>, Error>
    where
        T: ?Sized + tokio_postgres::ToStatement + Sync + Send,
    {
        let client: &tokio_postgres::Client = &self;
        client.query(query, params).await
    }
}
```

**Comment by LouisGariepy** [comment]
@bikeshedder Are you still open to support this feature? I see part of a working solution has been proposed in [in the comment above]( https://github.com/bikeshedder/deadpool/issues/56#issuecomment-1039920083). My use case is such that I generate functions which can then be used as single queries or mixed and matched to build transactions. This would really help with code duplication. Thanks :)
