### ISSUE TITLE
Can the Actix-web + deadpool-postgres example be updated?

### ISSUE THREAD

**Issue by gyfis** [bikeshedder/deadpool#72]
Hi, in the `actix-web + deadpool-postgres` example you mention that because `actix-web` doesn't support `tokio 0.3`, you need to use `deadpool 0.5.0`.

I probably don't fully understand how crates + dependencies work, but when I tested the latest `actix-web` + `deadpool-redis`, everything worked fine, with `Cargo.lock` showing that it uses `tokio = 0.2.23`. 

Is the incompatibility message necessary?

Thanks!

**Comment by bikeshedder** [comment]
`deadpool-redis` has not been updated to `deadpool 0.6` because mitsuhiko/redis-rs#405 has not been merged yet. The latest version of `deadpool-redis` uses `deadpool 0.5` and therefore you are using `tokio 0.2`.

The version numbers of the `deadpool-*` crates don't neccesarily match with the `deadpool` crate. Initially I was hoping to keep them in sync, but I need to bump the version whenever a new version of `redis` is released if the APIs don't match. In the case of redis I was lucky that 0.15, 0.16 and 0.17 were all compatible. With the upcoming 0.18 release it will no longer be compatible and require a release of `deadpool-redis 0.7` even though it is using `deadpool 0.6`. That's also the reason why `deadpool-redis 0.6` uses `deadpool 0.5` and not as you would expect `deadpool 0.6`.

The core of deadpool is executor independent. Only when using timeouts the actual deadpool code depends on the tokio executor. I'm currently working on a compatibility crate which removes this dependency and makes the core of deadpool runtime agnostic again. See #68

**Comment by bikeshedder** [comment]
I need to explain one more thing: If you were to use the `deadpool-redis` version from the repository you would find that it is using both `tokio 0.3` and `tokio 0.2`.

Output of `cargo tree` from inside the `deadpool-redis` directory:
```
...
├── deadpool v0.6.0 (/home/bikeshedder/projects/foss/deadpool)
...
│   └── tokio v0.3.3
...
├── redis v0.17.0
...
│   ├── combine v4.3.2
│   │   ├── bytes v0.5.6
│   │   ├── futures-util v0.3.7 (*)
│   │   ├── memchr v2.3.4
│   │   ├── pin-project-lite v0.1.11
│   │   └── tokio v0.2.22
...
│   ├── tokio v0.2.22 (*)
...
```

The current version of `deadpool-redis` in the repository also utilizes `tokio-compat-02` so it is compatible with a `tokio 0.3` runtime. I do not plan to release this on `crates.io` as I'm hoping that mitsuhiko/redis-rs#405 gets merged soon and I don't feel like `tokio-compat-*` should ever be part of a library release.

At the moment the `tokio 0.2/0.3` transition is kinda messy. I really hope all crates update to `tokio 0.3` soon and both `hyper` and `actix-web` get updated. With `hyper` you can patch the executor (https://github.com/bikeshedder/deadpool/blob/master/examples/postgres-hyper/src/main.rs#L87) but I haven't found a way to do the same with `actix-web`.

**Comment by gyfis** [comment]
I completely missed the version number mismatch, sorry! Thanks a lot for the explanation :) fingers crossed for the tokio migrations!

**Comment by bikeshedder** [comment]
Now that tokio 1.0 is released there might be a chance that the actix examples can be updated, soon: actix/actix-web#1813

**Comment by bikeshedder** [comment]
I just updated the examples using `actix-web 4.0.0-beta.1` which is based on `tokio 1`. See abf82c70de7982f6a3040404c31b74acf54af9e0
