### ISSUE TITLE
Delete single statement from statement cache

### ISSUE THREAD

**Issue by NAlexPear** [bikeshedder/deadpool#76]
When working with a schema that can be altered underneath the statement cache, that cache needs to be invalidated to avoid `cached statement cannot change return type`-flavored errors. Currently, the only the way to clear the `deadpool_postgres` statement cache is through the `clear()` method, which clears _all_ statements, even when only statement needs to be invalidated.

Would you accept a PR to expose a `delete` method on the statement cache to clear a single prepared statement by key?

EDIT: looking at the `StatementCache` more carefully, one would probably need a `delete_typed()`, too

**Comment by bikeshedder** [comment]
This sounds like a useful addition. :+1: 

Now that I'm thinking about it I guess you want to remove that statement from the statement cache of all clients whether they are currently part of the pool or in use. Right now calling the `clear` method on one `StatementCache` will not invalidate the other caches which might still have a cached statement which will result in an error if you execute the query using a different 

I feel like calling `clear` or `delete*` on a single StatementCache should be propagated to the statement caches of all Clients..

Implementing this is a bit more involved as the `Object` knows its `Pool` for returning itself, but the `Pool` doesn't know the objects it has handed out. In order to support this the `Pool` needs to remember the objects it has handed out and provide access to them via some kind of synchronized list. Using this list it would be possible to call a method on all objects and their statement caches.

Makes sense? What are your thoughts on that?

**Comment by NAlexPear** [comment]
> I feel like calling clear or delete* on a single StatementCache should be propagated to the statement caches of all Clients.

That makes a lot of sense. But I hadn't considered that the statement caches were scoped to the client instead of the pool... the fact that the caches aren't shared would reduce their usefulness considerably versus a single cache shared amongst multiple clients, right? Before I too much farther into the codebase, it seems like a shared cache at the `Pool` level instead of the `Object` level would both increase the cache hit rate and make synchronizing cache-busting easier between Clients.

**Comment by NAlexPear** [comment]
Got it :+1:. Then I'm not sure that there's a clear benefit to clearing the statement cache by `(statement, types)` across connections, since one could be clearing out perfectly good prepared statements elsewhere on an unrelated session (if I'm understanding this correctly). At least, there's a tradeoff to be made there. 

Perhaps one answer then would be to let users clear the statement caches attached to individual clients, and to also provide cache-clearing methods at the `Pool` level that clears every client cache.

**Comment by NAlexPear** [comment]
Went ahead and PR'd what I have for removing single statements, but this obviously doesn't cover the coordinated cross-`Client` case we were just discussing!

**Comment by bikeshedder** [comment]
PR a01d479639f8bdcfef8e3073ac2dd618ea15a5ad merged.

I added a new issue #78 to track the feature to globally `clear` caches and `remove` single statements from them.
