### ISSUE TITLE
Question about error message "No such file or directory" when password is empty in configuration

### ISSUE THREAD

**Issue by naemono** [bikeshedder/deadpool#82]
With simple example

main.rs
```
use tokio;
use dotenv::dotenv;
use tokio_postgres::{NoTls, Error};
use serde::{Deserialize};

#[derive(Debug)]
pub struct Blah {
	pub id: I32,
	pub name: String,
}

#[derive(Deserialize, Debug)]
pub struct Config {
    pub pg: deadpool_postgres::Config,
}

impl Config {
    pub fn from_env() -> Result<Self, ::config_crate::ConfigError> {
        let mut cfg = ::config_crate::Config::new();
        let env = ::config_crate::Environment::new().separator("__");
        cfg.merge(env)?;
        cfg.try_into()
    }
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    dotenv().ok();
    let cfg = Config::from_env().unwrap();
    let pool = cfg.pg.create_pool(NoTls).unwrap();

    let client = pool.get().await.unwrap();

    let rows = client
        .query("SELECT id, name, FROM fake_table", &[])
        .await?;

    let mut types = Vec::new();
    for row in rows {
        let b = Blah {
            id: row.get(0),
            name: row.get(1),
        };
        println!("blah: {:#?}", b);
        types.push(b);
    }

    Ok(())
}
```

Note I'm using `PG__PASS`, instead of `PG_PASSWORD` here, which was a typo on my part
.env
```
PG__HOST=127.0.0.1
PG__PORT=5432
PG__DBNAME=fakedb
PG__USER=myuser
PG__PASS=myvalidpass
```

This gives this error, which confused me for a huge amount of time:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Backend(Error { kind: Connect, cause: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" }) })', src/main.rs:54:35
```

This error is thrown when this is called
```
let client = pool.get().await.unwrap()
```

Frankly, I can't find exactly where this error is thrown in this library, but is there any chance that this could be a little clearer about what the failure is, or what file was not found?

Sorry I couldn't provide a PR to resolve this, but I'm relatively new to Rust.

**Comment by bikeshedder** [comment]
This error sounds like it is ignoring the `PG__HOST` environment variable and falling back to the default which is the UNIX domain socket located under `/run/postgres`, `/var/run/postgresql` or `/tmp` (checked in this order): https://docs.rs/deadpool-postgres/0.7.0/src/deadpool_postgres/config.rs.html#337

Could you check your config after calling `Config::from_env()` using `println!("{:?}", config)` and see whether the `.env` file is properly loaded.

**Comment by bikeshedder** [comment]
Did you figure out what's wrong?

**Comment by naemono** [comment]
Yeah, I was hinting at it here:

`Note I'm using PG__PASS, instead of PG__PASSWORD here, which was a typo on my part`

When updating the .env file to use `PG_PASSWORD`, things worked as expected.  I'm simply asking if a better error message, which indicates which missing file, and potentially what is producing this error would help the end user in these situations?

Coming in blind to a new actix api project using postgres, I have no idea where this error was being generated from (what part of the stack), but finally tracked it back to the deadpool code, which, honestly, took quite a decent amount of time.

**Comment by bikeshedder** [comment]
The error object actually is a `PoolError<tokio_postgres::Error>::Backend` which is merely a wrapper around the `tokio_postgres::Error` which in this case is of the kind `Connect` and wraps an `io::Error`. Also you are looking at the `Debug` string and not the `Display` which would have given you a more human readable error message like:

| An error occured while creating a new object: error connecting to server: No such file or directory

https://docs.rs/deadpool/0.7.0/src/deadpool/managed/errors.rs.html#73
https://docs.rs/tokio-postgres/0.7.0/src/tokio_postgres/error/mod.rs.html#377-403

This would still be quite cryptic if you didn't knew you're looking at a `deadpool` error message. So my advise is to never just call `unwrap()` but add some context information to the error. e.g. how about using `expect` instead of `unwrap`:

```rust
pool.get().await.expect("Could not get DB connection from pool")
```

Even better match the error and create some useful error messages for the user:

```rust
match pool.get().await {
    Ok(client) => { ... },
    Err(PoolError::Backend(e)) => { ... }
    ...
}
```

Or if you're doing central error handling you can even create your own wrapper enum:

```rust
#[derive(Debug)]
enum AppError {
    Pool(deadpool_postgres::Error)
}
```

Now you can simply wrap the errors that way:

```rust
pool.get().await.map_err(|e| AppError::Pool(e))?
```

If you implement `Display`, `Debug`, `Error` and `From<deadpool_postgres::Error>` you can even make the usage feel almost magical:

```rust
fn some_fn(pool: deadpool_postgres::Pool) -> Result<T, AppError> {
    let client = pool.get()?;
    ...
}
```

For an example how this could look like you can check out the `postgres-hyper` example which uses this pattern: https://github.com/bikeshedder/deadpool/blob/master/examples/postgres-hyper/src/main.rs#L32

----

So in a way the question is where the error message should be generated:

1. `std::io::Error` - this is Rust library code. Also there is little to be improved. It would be nice if the filename was part of the actual error message, but I can see why this is not the case as filenames are not guaranteed to be utf8 compatible or even present in case of an not found IO error.
2. `tokio_postgres::Error` - It could be helpful if the path that could not be opened was part of the error message.
3. `deadpool::PoolError` - Since deadpool is not limited to databases and `deadpool_postgres` doesn't have its own error type this would make it difficult to put a more meaningful error message here.
4. Your own code - By not just calling `.unwrap()` - even `.expect` is superior - you can actually add this kind of information yourself and get way better error messages. For other errors as well.

**Comment by naemono** [comment]
@bikeshedder I'd like to thank you for such a detailed explanation.  Hopefully just having this here will help someone in the future if they run into this error, and am not sure exactly where its source is. 

You're welcome to close this if you'd like.  Thanks again!
