### ISSUE TITLE
Release deadpool-redis

### ISSUE THREAD

**Issue by tyranron** [bikeshedder/deadpool#96]
Please, release new version of `deadpool-redis` crate with support of `redis 0.20` available in `master`. Current [`0.7.1` version dependends on `redis <= 0.20`](https://docs.rs/deadpool-redis/0.7.1).

**Comment by bikeshedder** [comment]
`deadpool-redis 0.7.1` already supports `redis 0.20`. As discussed in #90 this was a mistake and the upcoming versions of `deadpool-*` will no longer use version ranges because of this. A simple `cargo update` should already upgrade `redis` to `0.20` if you're only depending on `deadpool-redis` and not `redis`.

**Comment by tyranron** [comment]
@bikeshedder oh, right... that's `<=0.20`, not `<20`. Sorry >_<
